action: py38, msg: getenv
cwd: /home/pravin/Desktop/MLOPS/simple_app/.tox
cmd: /home/pravin/miniconda3/envs/wine_quality/bin/python -m virtualenv --no-download --python /usr/bin/python3.8 py38
RuntimeError: failed to query /usr/bin/python3.8 with code 1 err: 'Traceback (most recent call last):\n  File "/home/pravin/miniconda3/envs/wine_quality/lib/python3.9/site-packages/virtualenv/discovery/py_info.py", line 16, in <module>\n    from distutils import dist\nImportError: cannot import name \'dist\' from \'distutils\' (/usr/lib/python3.8/distutils/__init__.py)\n'
